# Generated by Django 3.1 on 2020-09-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_image', models.ImageField(default='default_project.png', upload_to='project_pics')),
                ('summary', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField()),
                ('author', models.CharField(max_length=120)),
                ('deploy_link', models.URLField(max_length=500)),
                ('tag', models.CharField(choices=[('personal', 'Personal'), ('freelance', 'Freelance'), ('professional', 'Professional')], default='personal', max_length=20)),
            ],
        ),
    ]
