# Generated by Django 3.1 on 2020-09-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deploy_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
