# Generated by Django 3.1 on 2020-08-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tag',
            field=models.CharField(choices=[('personal', 'Personal'), ('freelance', 'Freelance'), ('professional', 'Professional')], default='personal', max_length=20),
        ),
    ]
