# Generated by Django 3.1 on 2020-08-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200830_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='author',
            field=models.CharField(max_length=120),
        ),
    ]
