# Generated by Django 3.1 on 2020-08-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_report', '0002_auto_20200830_1510'),
        ('projects', '0004_auto_20200830_1505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
