# Generated by Django 3.1 on 2020-08-31 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200830_1510'),
        ('bug_report', '0003_auto_20200831_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
